version: '3'

services:
  proxy:
    image: traefik:v2.0
    ports:
      - "80:80" # The HTTP port to consume webs servers
      - "8080:8080" # The traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --api.insecure=true --providers.docker

  api:
    image: node:10.16
    volumes:
      - ./:/app
    restart: always
    working_dir: /app
    ports:
      - 3000:3000
    labels:
      - "traefik.http.routers.api.rule=Host(`api.localhost`)"
    command: yarn dev
