version: '3'

services:
  reverse-proxy:
    image: traefik:v2.0
    ports:
      - "80:80" # The HTTP port to consume webs servers
      - "8080:8080" # The traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --api.insecure=true --providers.docker

  node-ts:
    image: node:10.16
    build: .
    restart: always
    ports:
      - "3000:3000"
    labels:
      - "traefik.http.routers.node-ts.rule=Host(`node-ts.localhost`)"
